/* Generated by OpenAPI Generator. */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DetectorEvidence {
    #[serde(
        rename = "blockPolygonConfidence",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub block_polygon_confidence: Option<Option<f32>>,
    #[serde(rename = "configHash")]
    pub config_hash: String,
    #[serde(rename = "detectorId")]
    pub detector_id: String,
    #[serde(rename = "detectorVersion")]
    pub detector_version: String,
    #[serde(
        rename = "directionConfidence",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub direction_confidence: Option<Option<f32>>,
    #[serde(rename = "lineEvidence", skip_serializing_if = "Option::is_none")]
    pub line_evidence: Option<Vec<models::LineDetectorEvidence>>,
    #[serde(
        rename = "rotationConfidence",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub rotation_confidence: Option<Option<f32>>,
}
