/* Generated by OpenAPI Generator. */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LineDetectorEvidence {
    #[serde(
        rename = "polygonConfidence",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub polygon_confidence: Option<Option<f32>>,
    #[serde(
        rename = "textConfidence",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub text_confidence: Option<Option<f32>>,
}
