/* Generated by OpenAPI Generator. */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SourceGeometryEvidence {
    #[serde(rename = "blockPolygon")]
    pub block_polygon: Vec<Vec<f32>>,
    #[serde(rename = "detectorEvidence")]
    pub detector_evidence: Box<models::DetectorEvidence>,
    #[serde(rename = "linePolygons")]
    pub line_polygons: Vec<Vec<Vec<f32>>>,
    #[serde(rename = "schemaVersion")]
    pub schema_version: String,
    #[serde(rename = "sourceDirection")]
    pub source_direction: models::TextDirection,
    #[serde(rename = "sourceDirectionSource")]
    pub source_direction_source: String,
    #[serde(rename = "sourceRotationDeg")]
    pub source_rotation_deg: f32,
}
