/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type { LineDetectorEvidence } from './lineDetectorEvidence'

/**
 * Detector identity and the confidence channels that produced source
 * geometry.  Missing upstream evidence is represented by `None`, never by a
 * fabricated zero.
 */
export interface DetectorEvidence {
  /** @nullable */
  blockPolygonConfidence?: number | null
  /**
     * Canonical SHA-256 of the detector configuration, including endpoint
     * identity but excluding the image payload.
     */
  configHash: string
  detectorId: string
  detectorVersion: string
  /** @nullable */
  directionConfidence?: number | null
  lineEvidence?: LineDetectorEvidence[]
  /** @nullable */
  rotationConfidence?: number | null
}
