/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */

/**
 * Confidence attached to one line polygon.  Text recognition confidence and
 * polygon confidence are intentionally separate: many OCR services expose
 * only the former.
 */
export interface LineDetectorEvidence {
  /** @nullable */
  polygonConfidence?: number | null
  /** @nullable */
  textConfidence?: number | null
}
