/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type { DetectorEvidence } from './detectorEvidence'
import type { TextDirection } from './textDirection'

/**
 * Immutable OCR geometry as recorded when a text node is created.
 *
 * Target layout remains on [`Transform`] and `rendered_direction`; neither
 * translation nor rendering may rewrite this evidence.
 */
export interface SourceGeometryEvidence {
  blockPolygon: number[][]
  detectorEvidence: DetectorEvidence
  linePolygons: number[][][]
  schemaVersion: string
  sourceDirection: TextDirection
  sourceDirectionSource: string
  sourceRotationDeg: number
}
